# ==================================================================================================
# === FILE: sonar.conf
# === SYSTEM: Sonar WiFi keepalive daemon
# === CLEAN VERSION: v1.1
# ==================================================================================================

[sonar]
enable: true
debug_log: false
persistent_log: false
target: auto
count: 3
interval: 60
restart_threshold: 10
